import type { Store, StoreCode, AffiliateOffer } from "@/lib/types"

// Mock stores data
export const mockStores: Store[] = [
  {
    id: "1",
    country_code: "NO",
    slug: "bilkomponenter",
    domain: "bilkomponenter.no",
    name: "Bilkomponenter",
    logo_url: null,
    website_url: "https://bilkomponenter.no",
    description: "Bilkomponenter og reservedeler",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    country_code: "NO",
    slug: "dustin",
    domain: "dustin.no",
    name: "Dustin",
    logo_url: null,
    website_url: "https://dustin.no",
    description: "Elektronikk og datautstyr",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    country_code: "NO",
    slug: "komplett",
    domain: "komplett.no",
    name: "Komplett",
    logo_url: null,
    website_url: "https://komplett.no",
    description: "Elektronikk, datautstyr og gadgets",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    country_code: "NO",
    slug: "dokprint",
    domain: "dokprint.no",
    name: "DokPrint",
    logo_url: null,
    website_url: "https://dokprint.no",
    description: "Printere og kontorrekvisita",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    country_code: "NO",
    slug: "webhallen",
    domain: "webhallen.com",
    name: "Webhallen",
    logo_url: null,
    website_url: "https://webhallen.com",
    description: "Gaming og elektronikk",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    country_code: "NO",
    slug: "elkjop",
    domain: "elkjop.no",
    name: "Elkjøp",
    logo_url: null,
    website_url: "https://elkjop.no",
    description: "Elektronikk og husholdningsapparater",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    country_code: "UK",
    slug: "amazon",
    domain: "amazon.co.uk",
    name: "Amazon UK",
    logo_url: null,
    website_url: "https://amazon.co.uk",
    description: "Shopping for everything UK",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    country_code: "UK",
    slug: "currys",
    domain: "currys.co.uk",
    name: "Currys",
    logo_url: null,
    website_url: "https://currys.co.uk",
    description: "Electronics and home appliances",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    country_code: "UK",
    slug: "boots",
    domain: "boots.com",
    name: "Boots",
    logo_url: null,
    website_url: "https://boots.com",
    description: "Health and beauty products",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    country_code: "UK",
    slug: "argos",
    domain: "argos.co.uk",
    name: "Argos",
    logo_url: null,
    website_url: "https://argos.co.uk",
    description: "Retail for home and technology",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    country_code: "UK",
    slug: "next",
    domain: "next.co.uk",
    name: "Next",
    logo_url: null,
    website_url: "https://next.co.uk",
    description: "Fashion and home products",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    country_code: "UK",
    slug: "jd-sports",
    domain: "jdsports.co.uk",
    name: "JD Sports",
    logo_url: null,
    website_url: "https://jdsports.co.uk",
    description: "Sports and casual footwear",
    is_active: true,
    is_featured: true,
    reveal_cart_limit_override: null,
    reveal_product_limit_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock store codes
export const mockStoreCodes: StoreCode[] = [
  {
    id: "c1",
    store_domain: "bilkomponenter.no",
    code: "SPAR20",
    benefit_type: "percent_off",
    scope: "cart",
    value_percent: 20,
    value_amount: null,
    currency: "NOK",
    min_purchase_amount: 500,
    applies_to_product: null,
    tested_products_count: 15,
    terms: "Gjelder alle produkter",
    expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    last_tested_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "c2",
    store_domain: "bilkomponenter.no",
    code: "FRAKT",
    benefit_type: "free_shipping",
    scope: "cart",
    value_percent: null,
    value_amount: null,
    currency: "NOK",
    min_purchase_amount: 300,
    applies_to_product: null,
    tested_products_count: 8,
    terms: "Gratis frakt på ordre over 300kr",
    expires_at: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    last_tested_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "c3",
    store_domain: "dustin.no",
    code: "SUMMER2025",
    benefit_type: "percent_off",
    scope: "cart",
    value_percent: 15,
    value_amount: null,
    currency: "NOK",
    min_purchase_amount: 0,
    applies_to_product: null,
    tested_products_count: 22,
    terms: "Gjelder alle kategorier",
    expires_at: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    last_tested_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
]

// Mock affiliate offers
export const mockAffiliateOffers: AffiliateOffer[] = [
  {
    id: "aff1",
    country_code: "NO",
    slug: "amazon",
    store_name: "Amazon",
    store_domain: "amazon.no",
    logo_url: null,
    offer_type: "link",
    discount_type: null,
    discount_value: null,
    code: null,
    terms: "Affiliate link",
    affiliate_url: "https://amazon.no",
    is_active: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
