import type { Event } from "@/lib/types"

// localStorage key for events
const EVENTS_KEY = "dealtested_events_v1"

// In-memory event storage for when database is unavailable
const inMemoryEvents: Event[] = []

// Flag to stop retrying Supabase after a fatal error (e.g., missing table)
let supabaseFailed = false

/**
 * Check if Supabase env vars are available (browser-safe)
 */
function hasSupabaseEnv(): boolean {
  return !!(
    process.env.NEXT_PUBLIC_SUPABASE_URL && 
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  )
}

/**
 * Get browser Supabase client (lazy import to avoid SSR issues)
 */
async function getBrowserSupabaseClient() {
  if (typeof window === "undefined") return null
  if (!hasSupabaseEnv()) return null
  
  try {
    const { createClient } = await import("@/lib/supabase/client")
    return createClient()
  } catch {
    return null
  }
}

/**
 * Log an event - NEVER throws, always returns gracefully
 * Falls back to localStorage/in-memory if Supabase is unavailable or fails
 */
export async function logEvent(
  eventType: string,
  data: {
    guestId?: string
    storeDomain?: string
    countryCode?: string
    purchaseId?: string
    suspicious?: boolean
    meta?: Record<string, any>
  },
): Promise<{ ok: boolean; fallback?: "memory" | "localStorage" }> {
  // Build the event object for localStorage (uses country_code for backwards compat)
  const localEvent: Event = {
    id: `event_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    event_type: eventType,
    guest_id: data.guestId ?? null,
    store_domain: data.storeDomain ?? null,
    country_code: data.countryCode?.toLowerCase() ?? null,
    purchase_id: data.purchaseId ?? null,
    suspicious: data.suspicious ?? false,
    meta: data.meta ?? {},
    created_at: new Date().toISOString(),
  }

  // If Supabase previously failed with a fatal error, skip trying it again
  if (supabaseFailed) {
    return saveEventLocally(localEvent)
  }

  // Try to save to Supabase if available
  const supabase = await getBrowserSupabaseClient()
  if (supabase) {
    try {
      // Build Supabase event object (matches DB schema: country, not country_code)
      const dbEvent = {
        event_type: eventType,
        guest_id: data.guestId ?? null,
        store_domain: data.storeDomain ?? null,
        country: data.countryCode?.toLowerCase() ?? null, // DB uses 'country' column
        meta: data.meta ?? {},
        // created_at is auto-generated by DB
      }
      
      const { error } = await supabase.from("events").insert(dbEvent)
      
      if (error) {
        // Check for missing table error (PGRST205) or similar fatal errors
        const isFatalError = 
          error.code === "PGRST205" || 
          error.message?.includes("could not find") ||
          error.message?.includes("relation") ||
          error.code === "42P01" // PostgreSQL: undefined_table
        
        if (isFatalError) {
          // Mark Supabase as failed to avoid repeated attempts
          supabaseFailed = true
          console.warn("[v0] Events table not found in Supabase, falling back to local storage")
        } else {
          console.warn("[v0] Failed to log event to Supabase:", error.message)
        }
        
        // Fall back to local storage
        return saveEventLocally(localEvent)
      }
      
      return { ok: true }
    } catch (error) {
      // Any unexpected error - fall back gracefully
      console.warn("[v0] Failed to log event to database:", error instanceof Error ? error.message : "Unknown error")
      return saveEventLocally(localEvent)
    }
  }

  // No database available, use local fallback
  return saveEventLocally(localEvent)
}

/**
 * Save event to localStorage (client) or in-memory (server)
 * NEVER throws
 */
function saveEventLocally(event: Event): { ok: boolean; fallback: "memory" | "localStorage" } {
  // Try localStorage first (only works on client)
  if (typeof window !== "undefined") {
    try {
      const existing = localStorage.getItem(EVENTS_KEY)
      const events: Event[] = existing ? JSON.parse(existing) : []
      events.push(event)
      
      // Keep only the last 1000 events to avoid storage bloat
      const trimmed = events.slice(-1000)
      localStorage.setItem(EVENTS_KEY, JSON.stringify(trimmed))
      
      return { ok: true, fallback: "localStorage" }
    } catch (e) {
      // localStorage failed (quota, parsing error, etc.) - fall through to memory
    }
  }

  // Fall back to in-memory storage (server-side or localStorage failed)
  inMemoryEvents.push(event)
  
  // Keep in-memory events trimmed too
  if (inMemoryEvents.length > 1000) {
    inMemoryEvents.splice(0, inMemoryEvents.length - 1000)
  }
  
  return { ok: true, fallback: "memory" }
}

/**
 * Fetch events from Supabase (last 30 days, up to limit)
 * Returns null if Supabase is unavailable or fails
 */
export async function fetchEventsFromSupabase(options?: {
  country?: string
  limit?: number
  eventTypes?: string[]
}): Promise<Event[] | null> {
  const supabase = await getBrowserSupabaseClient()
  if (!supabase) return null
  
  try {
    const thirtyDaysAgo = new Date()
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)
    
    let query = supabase
      .from("events")
      .select("*")
      .gte("created_at", thirtyDaysAgo.toISOString())
      .order("created_at", { ascending: false })
      .limit(options?.limit ?? 2000)
    
    if (options?.country) {
      query = query.eq("country", options.country.toLowerCase())
    }
    
    if (options?.eventTypes && options.eventTypes.length > 0) {
      query = query.in("event_type", options.eventTypes)
    }
    
    const { data, error } = await query
    
    if (error) {
      console.warn("[v0] Failed to fetch events from Supabase:", error.message)
      return null
    }
    
    // Map Supabase 'country' field to 'country_code' for compatibility
    return (data || []).map((e) => ({
      ...e,
      country_code: e.country || e.country_code || null,
    }))
  } catch (error) {
    console.warn("[v0] Failed to fetch events:", error instanceof Error ? error.message : "Unknown error")
    return null
  }
}

/**
 * Get events from localStorage (client-side only)
 */
export function getLocalStorageEvents(): Event[] {
  if (typeof window === "undefined") return []
  try {
    const stored = localStorage.getItem(EVENTS_KEY)
    return stored ? JSON.parse(stored) : []
  } catch {
    return []
  }
}

/**
 * Get in-memory events (server-side)
 */
export function getInMemoryEvents(): Event[] {
  return inMemoryEvents
}

/**
 * Clear in-memory events
 */
export function clearInMemoryEvents(): void {
  inMemoryEvents.length = 0
}

/**
 * Clear localStorage events (client-side only)
 */
export function clearLocalStorageEvents(): void {
  if (typeof window === "undefined") return
  try {
    localStorage.removeItem(EVENTS_KEY)
  } catch {
    // Ignore errors
  }
}

/**
 * Reset the Supabase failed flag (useful for testing)
 */
export function resetSupabaseFailedFlag(): void {
  supabaseFailed = false
}
